
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:http://localhost:3306/db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update



